---
# Ansible managed
all:
    children:
        applications:
            children:
                app1:
                    children:
                        database:
                            hosts:
                            - database_uat_2
                            - database_uat_1
                        front_web:
                            hosts:
                            - front_uat_1
                            - front_uat_2
                        read_api:
                            hosts:
                            - read_uat_2
                            - read_uat_1
                        write_api:
                            hosts:
                            - write_uat_1
                            - write_uat_2
        locations:
            children:
                europe:
                    hosts:
                    - read_uat_2
                    - write_uat_1
                    - write_uat_2
                    - database_uat_2
                    - database_uat_1
                    - read_uat_1
                    - front_uat_1
                    - front_uat_2
