---
# -----------------------------------------------------------------------------
# Load application definition
# -----------------------------------------------------------------------------
- name: Load application definition
  hosts: localhost
  connection: local

  vars:
    application_servers_path: '../../infrastructure/generated/{{ application }}'

  tasks:

    # -----------------------------------------------------------------------------
    # Assert playbook execution
    # -----------------------------------------------------------------------------
    - name: Assert playbook execution
      block:
        # Check mandatory variables
        - name: Check mandatory variables
          assert:
              that:
                - application_servers_selected is defined
              fail_msg: "Missing mandatory variables"

    # -----------------------------------------------------------------------------
    # write servers output structure
    # -----------------------------------------------------------------------------
    - name: write servers output structure
      block:
        # Load application definition
        - name: write application folder
          file:
            path:  '{{ application_servers_path }}'
            state: 'directory'

        # Write servers
        - name: write servers
          template:
            dest: '{{ application_servers_path }}/{{ item.key }}.yml'
            src:  'server_defintion.yml.j2'
          loop: '{{ application_servers_selected | dict2items }}'
