---
# Ansible managed
all:
    children:
        applications:
            children:
                app2:
                    children:
                        r1:
                            hosts:
                                test1: {}
                                test2: {}
                                test3: {}
        locations:
            children:
                europe:
                    hosts:
                        test1: {}
                        test3: {}
                us:
                    hosts:
                        test2: {}
        os:
            children:
                linux:
                    children:
                        rhel75:
                            hosts:
                                test3: {}
                windows:
                    children:
                        win2k16:
                            hosts:
                                test1: {}
                        win2k19:
                            hosts:
                                test2: {}
        providers:
            children:
                azure:
                    hosts:
                        test1: {}
                        test2: {}
                vmware:
                    hosts:
                        test3: {}
