---
# Ansible managed
all:
    children:
        applications:
            children:
                app2:
                    children:
                        front_web:
                            hosts:
                                front_uat_1: {}
                        read_api:
                            hosts:
                                read_uat_1: {}
                                read_uat_2: {}
        locations:
            children:
                europe:
                    hosts:
                        front_uat_1: {}
                        read_uat_1: {}
                        read_uat_2: {}
        os:
            children:
                windows:
                    children:
                        win2k16:
                            hosts:
                                front_uat_1: {}
                                read_uat_1: {}
                                read_uat_2: {}
        providers:
            children:
                azure:
                    hosts:
                        front_uat_1: {}
                        read_uat_1: {}
                        read_uat_2: {}
