---
# Ansible managed
all:
    children:
        applications:
            children:
                app2:
                    children:
                        r1:
                            hosts:
                                test4: {}
        locations:
            children:
                europe:
                    hosts:
                        test4: {}
        os:
            children:
                linux:
                    children:
                        rhel75:
                            hosts:
                                test4: {}
        providers:
            children:
                rhev:
                    hosts:
                        test4: {}
