---
# Ansible managed
all:
    children:
        applications:
            children:
                app2:
                    children:
                        front_web:
                            hosts:
                            - front_uat_1
                        read_api:
                            hosts:
                            - read_uat_1
                            - read_uat_2
        locations:
            children:
                europe:
                    hosts:
                    - read_uat_1
                    - read_uat_2
                    - front_uat_1
